cache:
  paths:
  - vendor/

stages:
- test
- deploy

phpunit:php5.6:
  stage: test
  before_script:
  - bash ci/docker_install.sh > /dev/null
  - composer install --dev
  image: php:5.6
  allow_failure: true
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never --coverage-text
    
phpunit:php7.0:
  stage: test
  before_script:
  - bash ci/docker_install.sh > /dev/null
  - composer install --dev
  image: php:7.0
  allow_failure: true
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never --coverage-text

phpunit:php7.1:
  stage: test
  before_script:
  - bash ci/docker_install.sh > /dev/null
  - composer install --dev
  image: php:7.1
  allow_failure: true
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never --coverage-text
  
syncgithub:
  stage: deploy
  before_script:
  - apt update -yqq
  - apt install git -yqq
  image: debian:stable-backports
  allow_failure: true
  script:
  - git push --mirror git@github.com:dada87/libs.git
  when: on_success
  
