before_script:
- bash ci/docker_install.sh > /dev/null

phpunit:php5.6:
  image: php:5.6
  script:
    - phpunit --configuration phpunit.xml
    
phpunit:php7.0:
  image: php:7.0
  script:
    - phpunit --configuration phpunit.xml

phpunit:php7.1:
  image: php:7.1
  script:
    - phpunit --configuration phpunit.xml
