cache:
  paths:
  - vendor/

stages:
- build
- test
- deploy

build:php5.6:
  stage: build
  script:
  - bash ci/docker_install.sh > /dev/null
  - composer install --dev

build:php7.0:
  stage: build
  script:
  - bash ci/docker_install.sh > /dev/null
  - composer install --dev

build:php7.1:
  stage: build
  script:
  - bash ci/docker_install.sh > /dev/null
  - composer install --dev
  
phpunit:php5.6:
  stage: test
  image: php:5.6
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never --coverage-text
    
phpunit:php7.0:
  stage: test
  image: php:7.0
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never --coverage-text

phpunit:php7.1:
  stage: test
  image: php:7.1
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors=never --coverage-text
  
syncgithub:
  stage: deploy
  before_script:
  - apt update -yqq
  - apt install git -yqq
  image: debian:stable-backports
  allow_failure: true
  script:
  - git push --mirror git@github.com:dada87/libs.git
  when: on_success
  
