phpunit:php5.6:
  image: php:5.6
  script:
    - php vendor/bin/phpunit --colors tests
    
phpunit:php7.0:
  image: php:7.0
  script:
    - php vendor/bin/phpunit --colors tests

phpunit:php7.1:
  image: php:7.1
  script:
    - php vendor/bin/phpunit --colors tests
